config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('quiz.urls'))
]

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('test/<uuid:test_id>', views.TestDetailView.as_view(), name='test_detail'),
    path('test/page/<uuid:test_id>/', views.TestPageView.as_view(), name='test_page'),
    path('results/', views.ResultsListView.as_view(), name='results'),
    path('result/detail/<uuid:attempt_id>/', views.ResultDetailView.as_view(), name='result_detail'),

    path('test/list/', views.TestListView.as_view(), name='test_list'),
    path('add/questions/<uuid:test_id>/', views.QuestionAddView.as_view(), name='add_questions')
]

quiz/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from common.models import BaseModel
from django.urls import reverse
import random
from datetime import datetime

User = get_user_model()

class Science(BaseModel):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name=_("name"))

    def __str__(self):
        return self.name

class Test(BaseModel):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True, verbose_name="description")
    science = models.ForeignKey(Science, on_delete=models.CASCADE)
    duration = models.IntegerField(help_text="Testning davomiyligi daqiqalarda", verbose_name=_("duration"))
    attempts_allowed = models.IntegerField(help_text="Testni necha marta yechishga ruxsat beriladi", verbose_name=_("attemps allowed"))
    image = models.ImageField(upload_to='media/test/images', verbose_name=_("image"))
    number_of_questions = models.IntegerField(default=1, verbose_name=_("number of questions"))
    is_available = models.BooleanField(default=False)
    start_time = models.DateTimeField(verbose_name=_("start time"))
    end_time = models.DateTimeField(verbose_name=_("end time"))

    def __str__(self):
        return self.title
    
    def get_url(self, *args, **kwargs):
        return reverse('quiz:test_detail', kwargs={'test_id':self.id})
    
    @property
    def get_questions(self):
        questions = Question.objects.filter(test = self, is_available = True)
        questions = list(questions)
        try:
            questions = random.sample(questions, self.number_of_questions)
            return questions
        except Exception as e:
            return None
        

class Question(BaseModel):
    test = models.ForeignKey(Test, related_name="questions", on_delete=models.CASCADE, verbose_name=_("test"))
    name = models.TextField(verbose_name=_("name"))
    mark = models.IntegerField(default=1, verbose_name=_("mark"))
    is_multiple_choice = models.BooleanField(default=False, verbose_name=_("is multiple choice"))
    is_available = models.BooleanField(default=True, verbose_name=_("is available"))

    def __str__(self):
        return self.name
    
    @property
    def get_answers(self):
        answers = Answer.objects.filter(question = self)
        answers = list(answers)
        random.shuffle(answers)
        return answers

class Answer(BaseModel):
    question = models.ForeignKey(Question, related_name="answers", on_delete=models.CASCADE, verbose_name=_("question"))
    name = models.CharField(max_length=255, verbose_name=_("name"))
    is_correct = models.BooleanField(default=False, verbose_name=_("is correct"))

    def __str__(self):
        return self.name

class UserAttempt(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("user"))
    test = models.ForeignKey(Test, on_delete=models.CASCADE, verbose_name=_("test"))
    score = models.IntegerField(_("score"))
    time_taken = models.DurationField(_("time taken"))
    date_taken = models.DateTimeField(auto_now_add=True, verbose_name=_("date taken"))
    is_started = models.BooleanField(default=False, verbose_name=_('is started'))
    is_completed = models.BooleanField(default=False, verbose_name=_('is completed'))

    def __str__(self):
        return f"{self.user.get_full_name}-{self.test.title}"
    
    @property
    def get_time_taken(self):
        total_seconds = self.time_taken.total_seconds()
        minutes = int(total_seconds // 60)
        seconds = int(total_seconds % 60)
        return f"{minutes} minut {seconds} sekund"
    
    @property
    def get_total(self):
        total = round(self.score *100 / self.test.number_of_questions, 2)
        return total

class UserAnswer(BaseModel):
    attempt = models.ForeignKey(UserAttempt, related_name="user_answers", on_delete=models.CASCADE, verbose_name=_("attempt"))
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name=_("question"))
    selected_answer = models.ForeignKey(Answer, on_delete=models.CASCADE, verbose_name=_("selected answer"))
    is_correct = models.BooleanField(_("is correct"))

    def __str__(self):
        return f"{self.question.name}-{self.attempt.score}"
    

quiz/forms.py
from django import forms
from .models import Test

class QuestionsAddForm(forms.Form):
    questions = forms.CharField(widget = forms.Textarea(attrs={'rows':25, 'cols':40, 'class':'form-control'}))

quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django import http
from django.utils import timezone
from django.contrib import messages
from django.db import transaction
from django.core.cache import cache

from .forms import QuestionsAddForm
from .models import *

class HomePageView(View):
    def get(self, request):
        tests = Test.objects.filter(is_available = True)
        context = {
            'tests':tests,
        }
        return render(request, 'index.html', context)
    
class TestDetailView(LoginRequiredMixin, View):
    def get(self, request, test_id):
        test = get_object_or_404(Test, id = test_id)
        context = {
            'test':test,
            'this_cache':cache.get('hacktivist')
        }
        return render(request, 'quiz/test-detail.html', context)
    
class TestPageView(LoginRequiredMixin, View):
    def get(self, request, test_id):
        test = get_object_or_404(Test, id = test_id)
        
        questions = test.get_questions
        if not cache.get(request.user.username, False):
            cache.set(request.user.username, questions, timeout=60 * test.attempts_allowed)
            request.session['start_time'] = timezone.now().isoformat()
        attempt_count = UserAttempt.objects.filter(user = request.user, test = test).count()
        if attempt_count >= test.attempts_allowed:
            messages.error(request, f"Testga {test.attempts_allowed} marta urinish berilgan sizning urinishingiz tugadi.")
            return redirect('quiz:test_detail', test.id)
        
        context = {
            'test':test,
            'questions':cache.get(request.user.username)
        }
        user_attempt = UserAttempt.objects.filter(user = request.user, test = test).last()
        if user_attempt is None:
            UserAttempt.objects.create(
                user = request.user,
                test = test,
                score = 0,
                time_taken = timezone.timedelta(0),
                is_started = True
            )
        if not user_attempt.is_started and not user_attempt.is_completed:
            UserAttempt.objects.create(
                user = request.user,
                test = test,
                score = 0,
                time_taken = timezone.timedelta(0),
                is_started = True
            )
        return render(request, 'quiz/test-page.html', context)
    
    def post(self, request, test_id):
        test = get_object_or_404(Test, id = test_id)
        attempt = UserAttempt.objects.filter(user = request.user, test = test).last()
        if attempt.is_completed:
            return http.HttpResponse("Siz allaqachon testni tugatgansiz")
        try:
            with transaction.atomic():
                score = 0
                correct_answers_count = 0
                for question in Question.objects.filter(test = test):
                    selected_answer_id = request.POST.get(str(question.id))
                    if selected_answer_id:
                        selected_answer = Answer.objects.get(id = selected_answer_id)
                        print(selected_answer.name)
                        user_answer = UserAnswer.objects.create(
                            attempt = attempt,
                            question = question,
                            selected_answer = selected_answer,
                            is_correct = selected_answer.is_correct
                        )
                        user_answer.save()
                        if selected_answer.is_correct:
                            score += question.mark
                            correct_answers_count += 1
                attempt.score = score
                attempt.time_taken = timezone.now() - attempt.created
                attempt.is_completed = True
                attempt.save()
                cache.delete(request.user.username)
        except Exception as e:
            return http.HttpResponse(f"Xatolik yuz berdi. {e}")

        context = {
            "test":test,
            "attempt":attempt,
            "correct_answers_count":correct_answers_count
        }
            
        return redirect('quiz:result_detail', attempt.id)
    
class ResultsListView(LoginRequiredMixin, View):
    def get(self, request):
        attempts = UserAttempt.objects.all()
        user_answers = UserAnswer.objects.all()
        context = {
            "attempts":attempts,
            "user_answers":user_answers
        }
        return render(request, 'quiz/results.html', context)

class ResultDetailView(LoginRequiredMixin, View):
    def get(self, request, attempt_id):
        attempt = get_object_or_404(UserAttempt, id = attempt_id)
        user_answers = UserAnswer.objects.filter(attempt = attempt)
        context = {
            'user_answers':user_answers,
            'attempt':attempt
        }
        return render(request, "quiz/result-detail.html", context)
        

class TestListView(LoginRequiredMixin, View):
    def get(self, request):
        tests = Test.objects.all()
        context = {
            'tests':tests
        }
        return render(request, 'quiz/test-list.html', context)

class QuestionAddView(LoginRequiredMixin, View):
    def get(self, request, test_id):
        test = get_object_or_404(Test, id = test_id)
        form = QuestionsAddForm()
        return render(request, 'quiz/add-questions.html', {'form':form})
    def post(self, request, test_id):
        test = get_object_or_404(Test, id = test_id)
        form = QuestionsAddForm(request.POST)
        if form.is_valid():
            questions_data = form.cleaned_data['questions']
            try:
                questions_answers = questions_data.strip().split('===')
                
                for block in questions_answers:  
                    lines = block.strip().split("\n")
                    question_text = lines[0].lstrip('#') 
                    
                    question = Question.objects.create(
                        test = test,
                        name = question_text
                    )
                    
                    for line in lines[1:]:
                        is_correct = line.startswith("+")  
                        answer_text = line[1:].strip() 
                        Answer.objects.create(
                            question = question, 
                            name = answer_text,
                            is_correct = is_correct
                        )

                messages.success(request, "Savollar muvaffaqiyatli qo'shildi!")
                return http.HttpResponse("welcome")
            except Exception as e:
                messages.error(request, f"Xato yuz berdi: {e}")

templates/quiz/add-questions.html
{% extends 'base.html' %}


{% block title %} Test Sahifasi {% endblock %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Test Sahifasi</h4>

                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h1>{{ test.title }}</h1>
                        <form method="post" class="row mt-4">
                            {% csrf_token %}
                            {{ form.as_p }}
                            
                            <div class="col-sm-6">
                                <div class="text-sm-end mt-2 mt-sm-0">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="mdi mdi-share-all me-1"></i> Qo'shish </button>
                                </div>
                            </div> <!-- end col -->
                        </form> <!-- end row-->
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->

    </div> <!-- container-fluid -->
</div>
{% endblock %}

templates/quiz/result-detail.html
{% extends 'base.html' %}

{% block title %} Result Page {% endblock %}

{% block content %}

<div class="page-content">
    <div class="container-fluid">
        <div class="result-body">
            <main class="container">
            
            
                <div class="result-container">
                    <div class="result-questions">
                        {% for user_ans in user_answers %}
                        
                        <h5> {{ forloop.counter }}. {{ user_ans.question.name }}</h5>
                        {% if user_ans.selected_answer.is_correct %}
                        <div class="result-answer correct-answer">✔️ {{ user_ans.selected_answer.name }}</div>
                        {% else %}
                        <div class="result-answer wrong-answer">❌ {{ user_ans.selected_answer.name }}</div>
                        {% endif %}
        
                        {% endfor %}
                    </div>
            
                    <div class="result-summary">
                        <h3>Natijalar</h3>
                        <ul>
                            <li><b>Imtihon:</b> {{ attempt.test.title }} </li>
                            <li><b>O'qituvchi:</b> {{ attempt.test.science.teacher.get_full_name }} </li>
                            <li><b>O'quvchi:</b> {{ attempt.user.get_full_name}} </li>
                            <li><b>Sinf:</b> {{ attempt.user.pupil.pupil_class }} </li>
                            <li><b>Testga ketgan vaqt:</b> {{ attempt.get_time_taken }} </li>
                            <li><b>To'g'ri:</b> {{ attempt.score }}</li>
                            <li><b>Foiz:</b> {{ attempt.get_total }}%</li>
                        </ul>
                        <button class=".result-button" onclick="window.print()">Chop etish</button>
                    </div>
                </div>
            
            
            </main>
        </div>
    </div>
</div>

{% endblock %}

templates/quiz/result.html
{% extends 'base.html' %}

{% block title %} Result Page {% endblock %}

{% block content %}
<main class="page-content">
    <div class="page-fluid">
        <h1>{{ request.user.get_full_name }} - Test natijalari</h1>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Berilgan vaqt</th>
                <td scope="col">{{ test.duration }} minut</td>
              </tr>
              <tr>
                <th scope="col">Ketgazilgan vaqt</th>
                <td scope="col">{{ attempt.get_time_taken }}</td>
              </tr>
              <tr>
                <th scope="col">Savollar soni</th>
                <td scope="col">{{ test.number_of_questions }} ta</td>
              </tr>
              <tr>
                <th scope="col">To'g'ri javoblar soni</th>
                <td scope="col">{{ correct_answers_count }} ta</td>
              </tr>
              <tr>
                <th scope="col">Ball</th>
                <td scope="col">{{ attempt.score }}</td>
              </tr>
            </thead>
          </table>
        <a class="btn btn-lg btn-primary" href="{% url 'quiz:results' %}" role="button">Natijalar &raquo;</a>
    </div>
</main>
{% endblock %}

templates/quiz/test-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ test.title }} {% endblock %}

{% block content %}
<div class="page-content">
  <div class="container-fluid">

    <!-- start page title -->
    <div class="row">
      <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
          <h4 class="mb-sm-0 font-size-18">Test Ma'lumotlari {{ this_cache }}</h4>


        </div>
      </div>
    </div>
    <!-- end page title -->

    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-xl-6">
                <div class="product-detai-imgs">
                  <div class="row">
                    <div class="col-md-2 col-sm-3 col-4">
                      <div class="nav flex-column nav-pills " id="v-pills-tab" role="tablist"
                        aria-orientation="vertical">
                        <a class="nav-link active" id="product-1-tab" data-bs-toggle="pill" href="#product-1" role="tab"
                          aria-controls="product-1" aria-selected="true">
                          <img src="assets/images/product/img-7.png" alt="" class="img-fluid mx-auto d-block rounded">
                        </a>
                        <a class="nav-link" id="product-2-tab" data-bs-toggle="pill" href="#product-2" role="tab"
                          aria-controls="product-2" aria-selected="false">
                          <img src="assets/images/product/img-8.png" alt="" class="img-fluid mx-auto d-block rounded">
                        </a>
                        <a class="nav-link" id="product-3-tab" data-bs-toggle="pill" href="#product-3" role="tab"
                          aria-controls="product-3" aria-selected="false">
                          <img src="assets/images/product/img-7.png" alt="" class="img-fluid mx-auto d-block rounded">
                        </a>
                        <a class="nav-link" id="product-4-tab" data-bs-toggle="pill" href="#product-4" role="tab"
                          aria-controls="product-4" aria-selected="false">
                          <img src="assets/images/product/img-8.png" alt="" class="img-fluid mx-auto d-block rounded">
                        </a>
                      </div>
                    </div>
                    <div class="col-md-7 offset-md-1 col-sm-9 col-8">
                      <div class="tab-content" id="v-pills-tabContent">
                        <div class="tab-pane fade show active" id="product-1" role="tabpanel"
                          aria-labelledby="product-1-tab">
                          <div>
                            <img src="{{ test.image.url }}" alt="" class="img-fluid mx-auto d-block">
                          </div>
                        </div>
                      </div>
                      <div class="text-center">
                        <a href="{% url 'quiz:test_page' test.id %}" class="btn btn-primary waves-effect waves-light mt-2 me-1">
                          <i class="bx bx-cart me-2"></i> Boshlash
                        </a>
                        <a href="{% url 'quiz:home' %}" class="btn btn-secondary waves-effect  mt-2 waves-light">
                          <i class="bx bx-arrow-back"></i>Ortga
                        </a>
                      </div>

                    </div>
                  </div>
                </div>
              </div>

              <div class="col-xl-6">
                <div class="mt-4 mt-xl-3">
                  <a href="javascript: void(0);" class="text-primary"></a>
                  <h4 class="mt-1 mb-3">{{ test.title }} </h4>

                  <p class="text-muted float-start me-3">
                    O'tish bali
                  </p>

                  <h6 class="text-success text-uppercase">60 %</h6>
                  <br>
                  <p class="text-muted mb-4">{{ test.description }}</p>
                  <div class="row mb-3">
                    <div class="col-md-6">
                      <div>
                        <p class="text-muted"><i class="bx bx-time font-size-16 align-middle text-primary me-1"></i>
                          Berilgan vaqt</p>
                        <p class="text-muted"><i class="bx bx-stats font-size-16 align-middle text-primary me-1"></i>
                          Urinishlar soni</p>
                        <p class="text-muted"><i
                            class="bx bx-question-mark font-size-16 align-middle text-primary me-1"></i> Savollar soni
                        </p>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div>
                        <p class="text-muted"><i
                            class="bx bx-check-double font-size-16 align-middle text-primary me-1"></i> {{ test.duration }} minut</p>
                        <p class="text-muted"><i
                            class="bx bx-check-double font-size-16 align-middle text-primary me-1"></i> {{ test.attempts_allowed }} marta</p>
                        <p class="text-muted"><i
                            class="bx bx-check-double font-size-16 align-middle text-primary me-1"></i> {{ test.number_of_questions }} ta</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- end row -->

          </div>
        </div>
        <!-- end card -->
      </div>
    </div>
    <!-- end row -->

  </div> <!-- container-fluid -->
</div>
{% endblock %}

templates/quiz/test-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Result Page {% endblock %}

{% block content %}

<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col-sm-4">
                                <div class="search-box me-2 mb-2 d-inline-block">
                                    <div class="position-relative">
                                        <input type="text" class="form-control" placeholder="Search...">
                                        <i class="bx bx-search-alt search-icon"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="text-sm-end">
                                    <button type="button"
                                        class="btn btn-success btn-rounded waves-effect waves-light mb-2 me-2"><i
                                            class="mdi mdi-plus me-1"></i> Test qo'shish</button>
                                </div>
                            </div><!-- end col-->
                        </div>

                        <div class="table-responsive">
                            <table class="table align-middle table-nowrap table-check">
                                <thead class="table-light">
                                    <tr>
                                        <th class="align-middle">Tr</th>
                                        <th class="align-middle">Nomi</th>
                                        <th class="align-middle">Fan nomi</th>
                                        <th class="align-middle">boshlanish vaqti</th>
                                        <th class="align-middle">Tugash vaqti</th>
                                        <th class="align-middle">Statusi</th>
                                        <th class="align-middle">Berilgan vaqt</th>
                                        <th class="align-middle">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for test in tests %}
                                    <tr>
                                        <td><a href="javascript: void(0);" class="text-body fw-bold">{{ forloop.counter }} </a> </td>
                                        <td>{{ test.title }} </td>
                                        <td>
                                            {{ test.science.name }}
                                        </td>
                                        <td>
                                            {{ test.start_time }}
                                        </td>
                                        <td>
                                            {{ test.end_time|date }}
                                        </td>
                                        <td>
                                                {% if test.is_available %}
                                                <span class="badge badge-pill badge-soft-success font-size-12">Qo'shilgan</span>
                                                {% else %}
                                                <span class="badge badge-pill badge-soft-danger font-size-12">Qo'shilmagan</span>
                                                {% endif %}
                                        </td>
                                        <td>
                                            {{ test.duration }} minut
                                        </td>
                                        <td>
                                            <div class="d-flex gap-3">
                                                <a href="javascript:void(0);" class="text-success"><i
                                                        class="mdi mdi-pencil font-size-18"></i></a>
                                                <a href="javascript:void(0);" class="text-danger"><i
                                                        class="mdi mdi-delete font-size-18"></i></a>
                                                <a href="{% url 'quiz:add_questions' test.id %}" class="text-info"><i class="mdi mdi-plus-box-outline font-size-18" title="Savol qo'shish"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                        <ul class="pagination pagination-rounded justify-content-end mb-2">
                            <li class="page-item disabled">
                                <a class="page-link" href="javascript: void(0);" aria-label="Previous">
                                    <i class="mdi mdi-chevron-left"></i>
                                </a>
                            </li>
                            <li class="page-item active"><a class="page-link" href="javascript: void(0);">1</a></li>
                            <li class="page-item"><a class="page-link" href="javascript: void(0);">2</a></li>
                            <li class="page-item"><a class="page-link" href="javascript: void(0);">3</a></li>
                            <li class="page-item"><a class="page-link" href="javascript: void(0);">4</a></li>
                            <li class="page-item"><a class="page-link" href="javascript: void(0);">5</a></li>
                            <li class="page-item">
                                <a class="page-link" href="javascript: void(0);" aria-label="Next">
                                    <i class="mdi mdi-chevron-right"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div> <!-- container-fluid -->
</div>

{% endblock %}